name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Comprobar el repositorio
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Instalar Flyctl
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          echo "FLYCTL_INSTALL=$FLYCTL_INSTALL" >> $GITHUB_ENV
          echo "PATH=$FLYCTL_INSTALL/bin:$PATH" >> $GITHUB_ENV

      # 3. Autenticación en Fly.io
      - name: Authenticate with Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN

      # 4. Despliegue a Fly.io
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly deploy --remote-only
